openapi: 3.0.4
info:
  title: TerahAPI
  version: 0.0.1

paths: {}

components:
  schemas:
    ClientResponseDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        document:
          type: string
        address: 
          type: string
        email:
          type: string
        birthDate:
          type: string
          format: date
        phone:
          type: string
      required:
        - id
        - name
        - document

